### ISSUE TITLE
bluetoothctl is needed to run update_jade_fw.py on arch linux

### ISSUE THREAD

**Issue by pythcoiner** [Blockstream/Jade#120]
```
~/c/Jade master ?1 ❯ python3 update_jade_fw.py --serialport            Py Jade 13:16:48
Traceback (most recent call last):
  File "/home/pyth/c/Jade/update_jade_fw.py", line 12, in <module>
    from jadepy import JadeAPI, JadeError
  File "/home/pyth/c/Jade/jadepy/__init__.py", line 1, in <module>
    from .jade import JadeAPI
  File "/home/pyth/c/Jade/jadepy/jade.py", line 26, in <module>
    from .jade_ble import JadeBleImpl
  File "/home/pyth/c/Jade/jadepy/jade_ble.py", line 7, in <module>
    import bleak
  File "/home/pyth/c/Jade/venv/lib/python3.11/site-packages/bleak/__init__.py", line 41, in <module>
    if not _on_ci and not check_bluez_version(5, 43):
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pyth/c/Jade/venv/lib/python3.11/site-packages/bleak/backends/bluezdbus/__init__.py", line 17, in check_bluez_version
    p = subprocess.Popen(["bluetoothctl", "--version"], stdout=subprocess.PIPE)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'bluetoothctl'
```

this can be solved by installing bluez & bluez-utils:
```
sudo pacman -S bluez bluez-utils
```

**Comment by JamieDriver** [comment]
Nice.  We only really document Debian setup at the moment.
We can't ofc keep track of every linux distro - but hopefully it's straightforward enough to set up on the major distros.
I'll add a section to the wiki with this ^ info - cheers.
